spring:
  application:
    name: feedback-service
  
  datasource:
    url: jdbc:postgresql://localhost:5432/feedback_db
    username: postgres
    password: A190077abb
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  jackson:
    serialization:
      write-dates-as-timestamps: false

server:
  port: 8083

# Configuration JWT
jwt:
  secret: your-256-bit-secret-key-change-this-in-production-use-environment-variable
  expiration: 86400000 # 24 heures en millisecondes

# Configuration du microservice Catalog
catalog:
  service:
    url: http://localhost:8080
    endpoint:
      products: /products

# Logging
logging:
  level:
    root: INFO
    com.ecommerce.feedback: DEBUG
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG

