services:
  delivery-db:
    image: postgres:15
    container_name: delivery-postgres
    restart: always
    environment:
      POSTGRES_DB: delivery_db
      POSTGRES_USER: delivery_user
      POSTGRES_PASSWORD: delivery_pass
    ports:
      - "5432:5432"
    volumes:
      - delivery-db-data:/var/lib/postgresql/data
    networks:
      - delivery-network

volumes:
  delivery-db-data:

networks:
  delivery-network:
    driver: bridge
